---
- name: rsyslog install and start services
  hosts: all
  become: true

  tasks:
  - name: install Postgresql 
    apt:
      name: postgresql
      state: present

  - name: Ensure state
    service:
      name: postgresql
      state: stated
      enabled: true

  - name: install rsyslog version 8.2001.0
    apt:
      name: rsyslog=8.2001.0
      state: present

  - name: start rsyslog service
    service:
      name: rsyslog
      state: started
      enabled: true

  - name: add line to the syslog  /etc/rsyslog.conf
    blockinfile:
    dest: /etc/rsyslog.conf
    block: |
      module(load="imudp")
      input(type="imudp" port="5149")
      *.* @10.3.0.7:5149
      local0.*    /var/log/postgresql
      backup: yes
   
  - name: Enable logging for postgresql
    blockinfile:
    dest: /etc/postgresql/12/main/
    block: |
      log_statement = 'all'
      log_directory = 'pg_log'
      log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
      logging_collector = on
      log_min_error_statement = error
      log_destination = 'syslog' 

  - name: Restart Postgresql service
    ansible.builtin.service:
      name: postgresql
      state: restarted       

