---
- name: rsyslog install and start services
  hosts: all
  become: true

  tasks:
  - name: install rsyslog version 8.2001.0
    apt:
      name: rsyslog
      state: present

  - name: start rsyslog service
    service:
      name: rsyslog
      state: started
      enabled: true
  
  - name: Restart Postgresql service
    ansible.builtin.service:
      name: postgresql
      state: restarted       

